services:
    db:
        image: mysql
        restart: always
        container_name: db
        hostname: db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: bronze
            MYSQL_USER: pmoreira
            MYSQL_PASSWORD: pmoreira
        deploy:
            resources:
                limits:
                    memory: 500m
        networks:
            - webnet

    nifi:
        image: apache/nifi
        restart: always
        container_name: nifi
        hostname: nifi
        volumes:
            - ./data/nifi:/opt/nifi/nifi-current/flowfile_repository
            - ./data/util:/util
        environment:
            NIFI_WEB_HTTP_PORT: 9090
        ports:
            - 9090:9090
            - 8443:8443
        networks:
            - webnet

networks:
    webnet: